In [2]:
import numpy as np;
import pandas as pd;
from sklearn.model_selection import train_test_split as tts;
import matplotlib.pyplot as plt;

In [32]:
df = pd.read_csv(r"F:\Personal Projects\ML-and-DL-Optimisation-Methods\Datasets\housing.csv", sep=r"\s+", engine="python", encoding="utf-8");
#rint(df.head(10));
data_matrix = df.to_numpy();
print(data_matrix.shape);
r,c = data_matrix.shape;
X = data_matrix[:,0:-1];
#print(X.shape);
Y = data_matrix[:,-1];
Design_X = np.hstack((np.ones((r,1)),X));
print(Design_X);


X_train, X_test, Y_train, Y_test = tts(X,Y,train_size=0.8);
print(Y_train.shape)

(505, 14)
[[1.0000e+00 2.7310e-02 0.0000e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [1.0000e+00 2.7290e-02 0.0000e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 [1.0000e+00 3.2370e-02 0.0000e+00 ... 1.8700e+01 3.9463e+02 2.9400e+00]
 ...
 [1.0000e+00 6.0760e-02 0.0000e+00 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0000e+00 1.0959e-01 0.0000e+00 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [1.0000e+00 4.7410e-02 0.0000e+00 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
(404,)


In [65]:
def VGD(X,Y,step_size=0.0000001, iterations=500000):
    
    thetas = [];
    costs = [];

    m,n = X.shape;
    theta = np.zeros((n,1));
    Y = Y.reshape(m,1);
    
    

    for i in range(iterations):

        y_pred = X@theta;
        error = y_pred - Y;
        sqrd_error = np.square(error);
        cost = (1/(2*m))*np.sum(sqrd_error)
        grad = (1/m)*(X.T@(error));
        theta = theta - step_size*grad;
        thetas.append(theta.copy());
        costs.append(cost.copy());

    return theta, thetas, costs;




In [66]:
theta, thetas, costs = VGD(X_train,Y_train);

In [67]:
print(theta);

[[-0.16098777]
 [ 0.10535124]
 [-0.09185033]
 [ 0.01805052]
 [ 0.00984155]
 [ 0.30927775]
 [ 0.10961281]
 [ 0.06010841]
 [ 0.01644419]
 [ 0.00594534]
 [ 0.25499063]
 [ 0.03724284]
 [-0.62651848]]


In [68]:
def MAE(theta, X_test, Y_test):
    mae = np.mean((np.abs((X_test@theta)-Y_test)));
    return mae;

In [69]:
print(MAE(theta, X_test, Y_test));

8.748535964608797


In [1]:
# Stochastic Gradient Descent